name: Temp Publish Node.js (shoryukyzan/hot-module-reload)

on:
  push:
    branches:
      - "shoryukyzan/hot-module-reload"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com/
          scope: "@shoryukyzan"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: true

      - name: Build
        run: pnpm build

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm dlx semantic-release --branches shoryukyzan/hot-module-reload
